---

version: '3'
services:
  app_1:
    build:
      context: .
      dockerfile: './app/Dockerfile'
    ports:
      - '8001:8000'
  app_2:
    build:
      context: .
      dockerfile: './app/Dockerfile'
    ports:
      - '8002:8000'
  proxy:
    image: 'nginx:1.15.7'
    volumes:
      - './proxy/etc/nginx/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - app_1
      - app_2
    ports:
      - '80:80'
